name = "Llama2"
uuid = "0e620e9f-4534-4490-8f63-949aea0a85e1"
authors = ["Constantin-Paul Hertel <paul.hertel@aol.de>"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"

[compat]
BenchmarkTools = "1.6.3"
LoopVectorization = "0.12.173"
julia = "1.11"
