name = "Llama2"
uuid = "0e620e9f-4534-4490-8f63-949aea0a85e1"
authors = ["Constantin-Paul Hertel <paul.hertel@aol.de>"]
version = "1.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
LinearAlgebra = "1.11.0"
Random = "1.11.0"
StatsBase = "0.34.9"
julia = "1.11"
